/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DetailserviceImport } from './routes/detailservice'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DetailserviceRoute = DetailserviceImport.update({
  path: '/detailservice',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/detailservice': {
      id: '/detailservice'
      path: '/detailservice'
      fullPath: '/detailservice'
      preLoaderRoute: typeof DetailserviceImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/detailservice': typeof DetailserviceRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detailservice': typeof DetailserviceRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/detailservice': typeof DetailserviceRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/detailservice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/detailservice'
  id: '__root__' | '/' | '/detailservice'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailserviceRoute: typeof DetailserviceRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailserviceRoute: DetailserviceRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/detailservice"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/detailservice": {
      "filePath": "detailservice.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
